repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.11.18
    hooks:
      # Compile requirements
      - id: pip-compile
        args: [pyproject.toml, -o, requirements.txt]
